import {StyleSheet} from 'react-native';
import {colors} from '../../../../theme/colors';
import responsiveScale from '../../../../utils/responsiveScale';


const {scale, verticalScale, moderateScale} = responsiveScale;
export const styles = StyleSheet.create({
  main: {
    marginBottom: moderateScale(10),
  },
  wrapper: {
    backgroundColor: 'white',
  },
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  title: {
    backgroundColor: '#FF9200',
    color: 'white',
    fontSize: moderateScale(12),
    borderRadius: moderateScale(20),
    padding: moderateScale(3),
    width: scale(100),
    textAlign: 'center',
    marginTop: verticalScale(10),
    marginStart: moderateScale(20),
  },
  itemWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    margin: moderateScale(10),
    width: '65%',
    marginBottom: verticalScale(20),
  },
  row: {
    flexDirection: 'row',
    marginStart: moderateScale(30),
    margin: moderateScale(3),
    alignItems: 'center',
  },
  rateWrapper: {},
  txt: {
    backgroundColor: colors.greenColor,
    padding: moderateScale(5),
    margin: moderateScale(5),
    borderRadius: moderateScale(20),
    color: 'white',
    fontSize: moderateScale(11),
  },
  labelTitle: {
    fontSize: moderateScale(13),
    paddingBottom: verticalScale(10),
    fontWeight: '500',
    color: '#333333',
    width: '100%',
    textAlign: 'center',
  },
  img: {
    width: scale(70),
    height: verticalScale(80),
    marginStart: moderateScale(10),
  },
  label: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: moderateScale(5),
    backgroundColor: 'white',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: scale(0), height: scale(2)},
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(1.41),
    elevation: 0.7,
    marginBottom: moderateScale(45),
  },
  line: {
    width: '200%',
    backgroundColor: 'lightgray',
    height: scale(1),
    alignSelf: 'center',
  },
  wrapperTxt: {
    fontSize: moderateScale(15),
    color: '#333333',
    fontWeight: '500',
    padding: moderateScale(3),
    marginStart: moderateScale(5),
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    marginBottom: moderateScale(20),
    backgroundColor: 'white',
    borderRadius: moderateScale(20),
    padding: moderateScale(10),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: scale(0),
      height: scale(2),
    },
    shadowOpacity: 0.25,
    shadowRadius: moderateScale(4),
    elevation: moderateScale(5),
    width: '90%',
  },
  modalTitle: {
    fontSize: moderateScale(8),
    marginBottom: moderateScale(0),
    marginEnd:moderateScale(15),
    marginTop: moderateScale(1.5),
    left: moderateScale(15),
    color: 'white',
    alignItems: 'flex-end',
    backgroundColor: colors.greenColor,
    paddingHorizontal: moderateScale(6),
    paddingVertical: moderateScale(3.5),
    borderRadius: moderateScale(10),
  },
  modalText: {
    fontSize: moderateScale(14),
    textAlign: 'center',
    color: '#333333',
    padding: moderateScale(10),
  },
  modalLine: {
    backgroundColor: '#66AE7B',
    height: scale(1),
    width: scale(315),
    padding: moderateScale(0),
    marginTop: verticalScale(20),
  },
  openButton: {
    paddingTop: verticalScale(10),
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
  },
  confirmTxt: {
    color: colors.greenColor,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: moderateScale(11),
    paddingBottom: moderateScale(5),
  },
  description: {
    fontSize: moderateScale(10.5),
    color: '#333333',
    textAlign: 'center',
    paddingHorizontal: moderateScale(25),
    paddingTop: moderateScale(10),
    paddingBottom: moderateScale(5),
  },
});
